---
# tasks file for k8s-master 
- name: Installing Docker
  yum:
    name:
      - docker
      - iproute-tc
    state: present

- name: Starting Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Changing Docker cgroup driver to systemd
  copy:
    dest: /etc/docker/daemon.json
    content: |
              {
                "exec-opt": ["native.cgroupdriver=systemd"]
              }
  register: out

- name: Restarting docker service
  service: 
    name: docker
    state: restarted
  when: out.changed == true

- name: Configuring Yum repo for K8s
  yum_repository:
    name: kubernetes
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Installing kubeadm
  yum: 
    name: kubeadm

- name: Enabling kubelet service
  service:
    name: kubelet
    state: started
    enabled: yes

- name: Pulling required images
  shell: "kubeadm config images pull"
  changed_when: false

- name: Configuring k8s.conf
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
              net.bridge.bridge-nf-call-ip6tables = 1
              net.bridge.bridge-nf-call-iptables = 1

- name: Refreshing sysctl
  shell: "sysctl --system"
  changed_when: false

- name: Starting kubeadm service
  shell: "kubeadm init --pod-network-cidr={{ cidr }} --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"

- name: Creating .kube directory
  file:
    path: $HOME/.kube
    state: directory

- name: Copying all configuration files
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes

- name: Copying flannel script
  template:
    dest: /root
    src: kube-flannel.yml